version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

  scraper:
    build: ./data_loader
    environment:
      DB_NAME: main
      HOST_URL: postgres_container
      DB_USER: user
      DB_PASS: pass
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres: